name: Run Tests and Update Codebeamer

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run tests and save results
      - name: Run tests
        run: |
          npm install
          npm test